Feature/select menu
justinewright/project-squirrel-dragon pull request #17
Opened 2021-11-04 10:35 UTC by justinewright

## Feature description
The select menu feature allows users to update which sets they are currently tracking/collecting. 
The selection menu initially displays all the pokemon sets and user tracked sets (indicated by a check mark).

User can: 

-  tap to select or deselect. 
- cancel changes by selecting cancel.
- save changes by selecting done.
- search for specific set.

## Analysis and design
The select menu is presented as a sheet. Data is passed to it before it is presented.
MVVM.

## Solution description
The select menu keeps track of changes made - added and removed. Changes are only applied if the user wants.

App Login:
- users required to login 

Pokemon Collection Set:

- displays user sets
- when loading information the collection view is hidden
- if user has no sets, user is prompted to add some
- integrated with userSetRepository
- cell animation: fade
- updated cell looks

Select Menu:
- displays all pokemon sets
- displays user specific sets (indicated with check mark)
- uses custom search bar
- changes are saveable 
- changes are cancellable 
- cell animation: fade

User Set Repository:
- uses firebase client api
- changes snapshot data into user set data model

Firebase Client Api:
 - adds firebase login
 - adds crud functionality
 
Custom Searchbar:
- add button is optional
- new delegate method for when add button is pressed

## Output screenshots
Post the output screenshots, if a UI is affected or added due to this feature.
| | | |
|:-------------------------:|:-------------------------:|:-------------------------:|
|<img width="1604" alt="screen shot 2017-08-07 at 12 18 15 pm" src="https://user-images.githubusercontent.com/79986407/140295198-4fd2f086-45f6-4243-87cc-87e9df05bfab.png" >  |  <img width="1604" alt="screen shot 2017-08-07 at 12 18 15 pm" src="https://user-images.githubusercontent.com/79986407/140295260-0abe73c0-6eda-49a2-ab47-6c1ddd362527.png"> |<img width="1604" alt="screen shot 2017-08-07 at 12 18 15 pm" src="https://user-images.githubusercontent.com/79986407/140298512-e8290e6c-1f21-408d-9319-c12202dc0998.png">|
|Updated Home Screen|AddSetButton Pressed|Select Menu|
|<img width="1604" alt="screen shot 2017-08-07 at 12 18 15 pm" src="https://user-images.githubusercontent.com/79986407/140295397-306f6b51-f4a5-481a-9053-06d636e6bb2a.png" >  |  <img width="1604" alt="screen shot 2017-08-07 at 12 18 15 pm" src="https://user-images.githubusercontent.com/79986407/140295449-3cfbe164-a431-4859-9511-e5307fb9a1f3.png"> | <img width="1604" alt="screen shot 2017-08-07 at 12 18 15 pm" src="https://user-images.githubusercontent.com/79986407/140300680-0b0f5c1d-daee-4887-bf55-2404634df438.png">|
|Search Select Menu|Filter Select Menu|Login|

## Areas affected and ensured
- User Sets
- Pokemon Collection Sets
- Custom Search Bar
- App starting point

## Is there any existing behavior change of other features due to this code change?
Visuals.
Search bar has optional add button.
Users can add/delete their sets.

## Covered unit test cases
Yes. The select menu view model was tested.

2021-11-05 05:15 UTC, bgouws requested changes
Just a little bit of clean up, but otherwise very nice PR keep up the good work! 

Just a small side note: this PR was pretty big clients would ask you to break this down try not to go over 30 files is a pretty good rule of thumb. Generally the smaller the better 1-10 files is a pretty good size as well 😄 smaller PR's review pretty quick and get merged much faster than larger ones.

2021-11-08 05:10 UTC, bgouws requested changes
Just changing that variable name and then we are good to go 😄

2021-11-08 13:18 UTC, bgouws approved these changes

2021-11-09 18:50 UTC, VincentMoyo approved these changes

2021-11-09 21:35 UTC, merged