Feature/cards/tcg cards client api and repo
justinewright/project-squirrel-dragon pull request #29
Opened 2021-11-09 21:38 UTC by justinewright

## Feature description
- Adds enums to repository and apis for reusability
- Adds card models

2021-11-10 08:30 UTC, bgouws requested changes
Just some clean up.

2021-11-10 11:50 UTC, rvanderwesthuizen requested changes
Some small things otherwise all good

2021-11-10 13:49 UTC, AbdullahNana10 approved these changes

2021-11-11 04:27 UTC, bgouws approved these changes
Nice job 😄

2021-11-11 18:07 UTC, merged